include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude: [build/**, lib/gen/]
  errors:
    inference_failure_on_function_invocation: ignore

linter:
  rules:
    public_member_api_docs: false

formatter:
  page_width: 81