name: Deploy App - Web - Prod

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version Tag to Deploy
        required: true

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    name: Deploy App - Web - Prod
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version }}
      - uses: subosito/flutter-action@v2.15.0
        with:
          flutter-version: "3.19.0"
          channel: "stable"
      - run: flutter packages get
      - run: flutter build web --web-renderer canvaskit -t lib/main.dart
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CURLING_SCOREBOARD_PROD }}"
          projectId: curling-scoreboard-prod
          expires: 30d
          channelId: live
