name: Deploy App - Web - Dev

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    name: Deploy App - Web - Dev
    steps:
      - uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2.21.0
        with:
          flutter-version: "3.35.0"
          channel: "stable"
      - run: flutter packages get
      - run: flutter build web -t lib/main.dart
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CURLING_SCOREBOARD_DEV }}"
          projectId: curling-scoreboard-dev
          expires: 30d
          channelId: live
