name: Deploy - Web Dev

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    name: Deploy App Development
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          channel: "stable"
      - run: flutter packages get
      - run: flutter build web --web-renderer canvaskit -t lib/main.dart
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CURLING_SCOREBOARD_DEV }}"
          projectId: Curling-Scoreboard-DEV
          target: app_dev
          expires: 30d
          channelId: live
